### ISSUE TITLE
fromHex fails

### ISSUE THREAD

**Issue by kutyel** [escherlies/elm-color#2]
I tried this code and it was not working 🤔 
```elm
Color.fromHex "#1a79cb"
```
Defaulted to the transparent color...

**Comment by escherlies** [comment]
Hi @kutyel,

I tried to reproduce this but when I use `elm repl` and try the code, I works as expected:

```elm
> import Color
> Color.fromHex "#1a79cb"
Just (Rgba 0.10196078431372549 0.4745098039215686 0.796078431372549 1)
    : Maybe Color.Color
> Color.fromHexUnsafe "#1a79cb"
Rgba 0.10196078431372549 0.4745098039215686 0.796078431372549 1
    : Color.Color
> 
```

**Comment by kutyel** [comment]
Try outputting the colors and comparing them with the Hex version, I do not think they match 👀 
<img width="293" alt="Screenshot 2023-06-13 at 15 47 28" src="https://github.com/escherlies/elm-color/assets/5127501/e9a0f68b-18fb-415a-8ffc-600d1efe5ea2">

**Comment by escherlies** [comment]
You might want to use the `Color.toRgba255` function to get the rgb values as Int range from 0 to 255.

```elm
> Color.fromHexUnsafe "#1a79cb" |> Color.toRgba255
{ alpha = 255, blue = 203, green = 121, red = 26 }
    : { alpha : Int, blue : Int, green : Int, red : Int }
```

Please note that the Base type encodes the color channels as a percentage, a Float range from 0 to 1.
The other `Color.toRgba` function will output the color channels with a Float range from 0 to 1.

**Comment by kutyel** [comment]
But I want a `Color`, not
```elm
{ red : Int
, green : Int
, blue : Int
, alpha : Int
}
```
🤔

**Comment by escherlies** [comment]
Sorry but I don't understand your problem. Could you be more specific? Maybe with a complete example in what you are trying to achieve?

**Comment by kutyel** [comment]
The problem is quite easy, with our internal `Color.fromHex` function and the one in avh4/elm-color (copying from it) this is the end result:
<img width="209" alt="Screenshot 2023-06-14 at 11 36 29" src="https://github.com/escherlies/elm-color/assets/5127501/2db78e7f-a43c-4f6f-968d-fd19a9731a44">
But if I use `Color.fromHexUnsafe` for the same `#1a79cb` color I get this:
<img width="287" alt="Screenshot 2023-06-14 at 11 39 16" src="https://github.com/escherlies/elm-color/assets/5127501/469cc591-8acd-4c59-9ca3-7dabe48e7179">
So I think the logical conclusion is that there is something wrong with the library 🤔

**Comment by escherlies** [comment]
What are you using to rendering the color?
How do you convert the color back?
